In [1]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.3.1


## Initialization

In [2]:
# SCALARS
var1 = tf.Variable(123, dtype = tf.int16)
var2 = tf.Variable(1.2, dtype = tf.float32)
var3 = tf.Variable("X", dtype = tf.string)
print(var1)
print(var2)
print(var3)

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=123>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.2>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'X'>


In [3]:
# VECTORS
var1 = tf.Variable([1,2,3,4,5], dtype = tf.float32)
var2 = tf.Variable([[1,2,3,4,5],[6,7,8,9,0]], dtype = tf.float32)
print(var1)
print(var2)

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 5) dtype=float32, numpy=
array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]], dtype=float32)>


In [4]:
# GET VALUE
var1.numpy()

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
# CONST (for asserting dtype - refer docs)
const1 = tf.constant([1,2,3,4,5], dtype = tf.float32)
print(const1)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [6]:
tf.eye(2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [7]:
tf.zeros((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [8]:
tf.ones((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [9]:
tf.random.normal((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.35871753, -1.5713143 ,  0.23083746],
       [ 0.387041  , -0.8795477 , -1.0243611 ],
       [-0.2777654 , -1.4723828 ,  2.9308202 ]], dtype=float32)>

## Reshape, Squeeze/Unsqueeze, Flatten

In [10]:
data = np.random.randint(0,10,(4,3))
t = tf.Variable(data)

print(t)

<tf.Variable 'Variable:0' shape=(4, 3) dtype=int64, numpy=
array([[5, 0, 8],
       [1, 8, 1],
       [1, 0, 7],
       [0, 5, 7]])>


In [11]:
# RESHAPE
t1 = tf.reshape(t, (6,2))
print(t1)

tf.Tensor(
[[5 0]
 [8 1]
 [8 1]
 [1 0]
 [7 0]
 [5 7]], shape=(6, 2), dtype=int64)


In [12]:
# RESHAPE
t1 = tf.reshape(t, (3,-1))  # 3 is one of the desired dimensions, -1 automatically figures out the other dimension
print(t1)

tf.Tensor(
[[5 0 8 1]
 [8 1 1 0]
 [7 0 5 7]], shape=(3, 4), dtype=int64)


In [14]:
# UNSQUEEZE
t0 = tf.reshape(t,(1,1,-1))
print(t0)

# SQUEEZE
t1 = tf.squeeze(t0)
print(t1)

tf.Tensor([[[5 0 8 1 8 1 1 0 7 0 5 7]]], shape=(1, 1, 12), dtype=int64)
tf.Tensor([5 0 8 1 8 1 1 0 7 0 5 7], shape=(12,), dtype=int64)


In [15]:
# UNSQUEEZE MULTI DIMENSIONS
t0 = tf.reshape(t,(1,1,1,-1))
print(t0)

# SQUEEZE SPECIFIC DIMENSIONS (default - all dimensions with 1)
t1 = tf.squeeze(t0, axis=1)
print(t1)

tf.Tensor([[[[5 0 8 1 8 1 1 0 7 0 5 7]]]], shape=(1, 1, 1, 12), dtype=int64)
tf.Tensor([[[5 0 8 1 8 1 1 0 7 0 5 7]]], shape=(1, 1, 12), dtype=int64)


In [16]:
# FLATTEN
t1 = tf.reshape(t,(-1))
print(t1)

tf.Tensor([5 0 8 1 8 1 1 0 7 0 5 7], shape=(12,), dtype=int64)


## Reduction

In [17]:
%%capture

# AVAILABLE
tf.argmax
tf.argmin
tf.reduce_max
tf.reduce_min
tf.reduce_sum
tf.reduce_prod
tf.reduce_mean
tf.reduce_any
tf.reduce_all
tf.reduce_logsumexp

In [18]:
data = np.random.randint(0,50,(3,3))
t = tf.Variable(data)

print(t)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int64, numpy=
array([[26, 48, 23],
       [ 3, 16, 41],
       [ 0,  1, 45]])>


In [19]:
max1 = tf.reduce_max(t)          # OVERALL MAX
max2 = tf.reduce_max(t, axis=1)
print("MAX1:", max1.numpy())
print("MAX2:", max2.numpy())
argmax2 = tf.argmax(t, axis=1)   # default - axis=0 
print("ARG2:", argmax2.numpy())

MAX1: 48
MAX2: [48 41 45]
ARG2: [1 2 2]


In [20]:
sum1 = tf.reduce_sum(t) # OVERALL SUM
sum2 = tf.reduce_sum(t, axis=1)
print("SUM1:", sum1.numpy())
print("SUM2:", sum2.numpy())

SUM1: 203
SUM2: [97 60 46]
